### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by EYH0602**
add relative path for `include`.

### CODE REVIEW

**Review by kingst — COMMENTED** [review]
Thanks for the PR! The `dcash` wallet isn't supposed to be able to access those classes, they're for the server only. Is there a class in particular that you want to use in the wallet side that is in the server side and _not_ part of `../shared`?

**Comment by EYH0602** [comment]
> Thanks for the PR! The `dcash` wallet isn't supposed to be able to access those classes, they're for the server only. Is there a class in particular that you want to use in the wallet side that is in the server side and _not_ part of `../shared`?

This PR was a mistake. I was trying to add some error handling to my `dcash` client and though it would be good to have access to `ClientError.h`. Then I fount out that I wouldn't be about to receive those error code anyway.

**Comment by kingst** [comment]
From the wallet you can pull the status code out of the `HttpClientResponse` object if you need to see it

**Comment by EYH0602** [comment]
> From the wallet you can pull the status code out of the `HttpClientResponse` object if you need to see it

Yes. I see that `HttpClientResponse` object can tell both if its success and the status. Thanks.

**Pull request closed without merging**
